// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmI9IDhPfZPa4I3uK53KlnFIoZos7dSNY',
    appId: '1:261159882169:web:05b4c32cbfbfbe83cefa68',
    messagingSenderId: '261159882169',
    projectId: 'operational-3b1b6',
    authDomain: 'operational-3b1b6.firebaseapp.com',
    storageBucket: 'operational-3b1b6.appspot.com',
    measurementId: 'G-29RQYN1XT6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSmgv3vBj3hiZIabvWwpuuTwcIl8w0w3k',
    appId: '1:261159882169:android:ad741173fe1d237acefa68',
    messagingSenderId: '261159882169',
    projectId: 'operational-3b1b6',
    storageBucket: 'operational-3b1b6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBczS7q4ar4u1C0QpJNX2y_SN6sa1hxUFc',
    appId: '1:261159882169:ios:47bbabe495c0b065cefa68',
    messagingSenderId: '261159882169',
    projectId: 'operational-3b1b6',
    storageBucket: 'operational-3b1b6.appspot.com',
    iosBundleId: 'com.example.operational',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBczS7q4ar4u1C0QpJNX2y_SN6sa1hxUFc',
    appId: '1:261159882169:ios:47bbabe495c0b065cefa68',
    messagingSenderId: '261159882169',
    projectId: 'operational-3b1b6',
    storageBucket: 'operational-3b1b6.appspot.com',
    iosBundleId: 'com.example.operational',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAmI9IDhPfZPa4I3uK53KlnFIoZos7dSNY',
    appId: '1:261159882169:web:c4ab6dfd0299b885cefa68',
    messagingSenderId: '261159882169',
    projectId: 'operational-3b1b6',
    authDomain: 'operational-3b1b6.firebaseapp.com',
    storageBucket: 'operational-3b1b6.appspot.com',
    measurementId: 'G-E28Z0NRW5W',
  );
}
